"""empty message

Revision ID: 033262030ecc
Revises: e4c583ad15de
Create Date: 2021-10-31 11:26:16.097908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033262030ecc'
down_revision = 'e4c583ad15de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_column('users', 'laste_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('laste_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
