"""empty message

Revision ID: 2213f615a44c
Revises: 310b2065b48e
Create Date: 2022-01-01 22:39:40.316264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2213f615a44c'
down_revision = '310b2065b48e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plain_clothing', sa.Column('quantity_debit_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plain_clothing', 'quantity_debit_count')
    # ### end Alembic commands ###
