"""empty message

Revision ID: 310b2065b48e
Revises: b7970b8751d1
Create Date: 2021-12-31 00:50:21.890159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310b2065b48e'
down_revision = 'b7970b8751d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_supplier_product_sku_id_fkey', 'product_supplier', type_='foreignkey')
    op.drop_constraint('product_supplier_product_id_fkey', 'product_supplier', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('product_supplier_product_id_fkey', 'product_supplier', 'incoming_products', ['product_id'], ['id'])
    op.create_foreign_key('product_supplier_product_sku_id_fkey', 'product_supplier', 'incoming_products', ['product_sku_id'], ['sku_id'])
    # ### end Alembic commands ###
