"""empty message

Revision ID: 4d210b48e0b8
Revises: a56cccbc6f99
Create Date: 2021-12-28 10:20:35.303557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d210b48e0b8'
down_revision = 'a56cccbc6f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incoming_products', 'updated_at')
    # ### end Alembic commands ###
