"""empty message

Revision ID: 4eb101a6f02b
Revises: 2213f615a44c
Create Date: 2022-01-01 23:05:22.380359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb101a6f02b'
down_revision = '2213f615a44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embroidery', sa.Column('quantity_debit_count', sa.Integer(), nullable=True))
    op.add_column('htp', sa.Column('quantity_debit_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('htp', 'quantity_debit_count')
    op.drop_column('embroidery', 'quantity_debit_count')
    # ### end Alembic commands ###
