"""empty message

Revision ID: a334c8fcde6e
Revises: 4d210b48e0b8
Create Date: 2021-12-31 00:26:44.077522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a334c8fcde6e'
down_revision = '4d210b48e0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plain_clothing', sa.Column('sku_id', sa.Integer(), nullable=True))
    op.add_column('plain_clothing', sa.Column('location', sa.String(), nullable=True))
    op.add_column('plain_clothing', sa.Column('reorder_point', sa.Integer(), nullable=True))
    op.add_column('plain_clothing', sa.Column('demand', sa.Integer(), nullable=True))
    op.add_column('plain_clothing', sa.Column('total_quantity', sa.Integer(), nullable=True))
    op.add_column('plain_clothing', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('plain_clothing', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint('plain_clothing_incoming_product_id_key', 'plain_clothing', type_='unique')
    op.drop_constraint('plain_clothing_incoming_product_sku_id_key', 'plain_clothing', type_='unique')
    op.create_unique_constraint(None, 'plain_clothing', ['sku_id'])
    op.drop_constraint('plain_clothing_incoming_product_id_fkey', 'plain_clothing', type_='foreignkey')
    op.drop_constraint('plain_clothing_incoming_product_sku_id_fkey', 'plain_clothing', type_='foreignkey')
    op.drop_column('plain_clothing', 'incoming_product_sku_id')
    op.drop_column('plain_clothing', 'incoming_product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plain_clothing', sa.Column('incoming_product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plain_clothing', sa.Column('incoming_product_sku_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('plain_clothing_incoming_product_sku_id_fkey', 'plain_clothing', 'incoming_products', ['incoming_product_sku_id'], ['sku_id'])
    op.create_foreign_key('plain_clothing_incoming_product_id_fkey', 'plain_clothing', 'incoming_products', ['incoming_product_id'], ['id'])
    op.drop_constraint(None, 'plain_clothing', type_='unique')
    op.create_unique_constraint('plain_clothing_incoming_product_sku_id_key', 'plain_clothing', ['incoming_product_sku_id'])
    op.create_unique_constraint('plain_clothing_incoming_product_id_key', 'plain_clothing', ['incoming_product_id'])
    op.drop_column('plain_clothing', 'updated_at')
    op.drop_column('plain_clothing', 'created_at')
    op.drop_column('plain_clothing', 'total_quantity')
    op.drop_column('plain_clothing', 'demand')
    op.drop_column('plain_clothing', 'reorder_point')
    op.drop_column('plain_clothing', 'location')
    op.drop_column('plain_clothing', 'sku_id')
    # ### end Alembic commands ###
