"""empty message

Revision ID: a56cccbc6f99
Revises: dd8e603d32b9
Create Date: 2021-12-28 09:40:39.667825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56cccbc6f99'
down_revision = 'dd8e603d32b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_products', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('incoming_products', 'location_quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_products', sa.Column('location_quantity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('incoming_products', 'location')
    # ### end Alembic commands ###
