"""empty message

Revision ID: a5cbce074f0f
Revises: 9dcdf21de31d
Create Date: 2021-12-26 13:17:41.166997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5cbce074f0f'
down_revision = '9dcdf21de31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incoming_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('reorder_point', sa.Integer(), nullable=True),
    sa.Column('demand', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id')
    )
    op.create_table('plain_clothing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incoming_product_id', sa.Integer(), nullable=True),
    sa.Column('incoming_product_sku_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('sleeve_type', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['incoming_product_id'], ['incoming_products.id'], ),
    sa.ForeignKeyConstraint(['incoming_product_sku_id'], ['incoming_products.sku_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incoming_product_id'),
    sa.UniqueConstraint('incoming_product_sku_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plain_clothing')
    op.drop_table('incoming_products')
    # ### end Alembic commands ###
