"""empty message

Revision ID: b1ea58ec52b9
Revises: a318748b84f7
Create Date: 2022-01-15 19:49:29.235518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ea58ec52b9'
down_revision = 'a318748b84f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('design_clothing', existing_type=sa.Integer(),
                    type_=sa.String(), nullable=False)
    op.add_column('design_imprinted_htp', existing_type=sa.Integer(),
                  type_=sa.String(), nullable=False)

    # ### end Alembic commands ###
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('design_imprinted_htp')
    op.drop_table('design_clothing')
    # ### end Alembic commands ###
