"""empty message

Revision ID: be88579480a6
Revises: ecf83797d3b8
Create Date: 2021-11-16 08:52:18.558743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be88579480a6'
down_revision = 'ecf83797d3b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_items', 'quantity')
    op.drop_column('raw_items', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_items', sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('raw_items', sa.Column('quantity', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
