"""empty message

Revision ID: dd8e603d32b9
Revises: f29817c0908b
Create Date: 2021-12-28 09:33:49.991698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8e603d32b9'
down_revision = 'f29817c0908b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_products', sa.Column('location_quantity', sa.String(), nullable=True))
    op.add_column('incoming_products', sa.Column('total_quantity', sa.Integer(), nullable=True))
    op.add_column('incoming_products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('incoming_products', 'quantity')
    op.drop_column('incoming_products', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_products', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incoming_products', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('incoming_products', 'created_at')
    op.drop_column('incoming_products', 'total_quantity')
    op.drop_column('incoming_products', 'location_quantity')
    # ### end Alembic commands ###
