"""empty message

Revision ID: ecf83797d3b8
Revises: 3fd3e83b47d3
Create Date: 2021-11-08 08:57:35.700806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf83797d3b8'
down_revision = '3fd3e83b47d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_items', sa.Column(
        'sku_id', sa.Integer(), nullable=True))
    op.add_column('raw_items', sa.Column(
        'category', sa.String(), nullable=True))
    op.add_column('raw_items', sa.Column('colour', sa.String(), nullable=True))
    op.add_column('raw_items', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('raw_items', sa.Column(
        'quantity', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'raw_items', ['sku_id'])
    op.drop_column('raw_items', 'credits')
    op.drop_column('raw_items', 'description')
    op.drop_column('raw_items', 'term')
    op.drop_column('raw_items', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_items', sa.Column(
        'title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('raw_items', sa.Column(
        'term', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('raw_items', sa.Column(
        'description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('raw_items', sa.Column(
        'credits', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'raw_items', type_='unique')
    op.drop_column('raw_items', 'quantity')
    op.drop_column('raw_items', 'size')
    op.drop_column('raw_items', 'colour')
    op.drop_column('raw_items', 'category')
    op.drop_column('raw_items', 'sku_id')
    # ### end Alembic commands ###
